### ISSUE TITLE
php-cli dependency fail despite it being available

### ISSUE THREAD

**Issue by maciej-gurban** [rmccue/puppet-wp#25]
The following prevents me from creating any sites (or working with puppet-wp at all)

```
if ! defined(Package["$phpprefix-cli"]) {
    package { "$phpprefix-cli":
        ensure => installed,
    }
}
```

My `rpm -q php-cli`
php-cli-5.3.3-27.el6_5.x86_64

Php installed using example42/php from puppetforge.  Manual 'php' command-line executions work just fine. Manually installed wp-cli and all its functionalities are in tact. Any ideas?

**Comment by rmccue** [comment]
This should be fixed by #37, which allows:

```
class { 'wp':
    php_package => 'php',
}
```
